angular.module('greenTourism', [
  'ngRoute',
  'welcomePage',
  'events',
  'signup',
  'signin',
  'placeList',
  'trackList',
  'userProfile',
  'event',
  'blogList',
  'blog',
  'calendar',
  'ngAnimate',
  'ui.bootstrap',
  'locationPlaces',
  'popularPlaces',
  'placeDetail'
]);
